### ISSUE TITLE
allahvar

### ISSUE THREAD

**Issue by SpongeBed81** [Okeanos-0/c-learning#1]
beyler biliyo musunuz bilemem ama allah var inanabiliyo musunuz???!*?!? bence de allah var aga yani allah yok diyenleri götten sikmeye geliyorum ben şahsen

**Comment by Okeanos-0** [comment]
SpongeBed81 dediğimiz kullanıcı böyle terbiyesiz bir insanmış ben onun adına çok utandım.

**Comment by H6PSRjmuIeu7mSRxhQI5** [comment]
allahyok b
